---
title: "Site-by-Site Plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r read in data}
chrom2.site <- read.csv(file="/Users/nataliehofmeister/Documents/Ch3-Global-RESEQ/analysis/R/input/chrom2/chrom2.SiteStats.csv")
```

```{r plotting site-by-site fst and pi}

quartz(height=5,width=7)
options(scipen=999)
par(mfrow=c(2,1))
par(mar=c(0,2,0.5,2))
plot(chrom2.site$POS, chrom2.site$WEIR_AND_COCKERHAM_FST_AUUK,type="n",bty="n", axes=FALSE,ylim=c(0,1))
points(chrom2.site$POS, chrom2.site$WEIR_AND_COCKERHAM_FST_AUUK,pch=16,cex=0.5,col = "#F2C14E",bty="n", axes=FALSE,ylim=c(0,1))
par(new=T)
points(chrom2.site$POS, chrom2.site$WEIR_AND_COCKERHAM_FST_UKUS, pch=16,cex=0.5, col = "#2c81a8", bty="n", axes=FALSE,  ylim=c(0,1))
par(new=T)
plot(chrom2.site$POS, chrom2.site$WEIR_AND_COCKERHAM_FST_USAU, pch=16,cex=0.5,col = "grey50", bty="n", axes=FALSE,  ylim=c(0,1))
axis(side=2,ylim=c(-0.2,1))
par(mar=c(1,2,1,2))
plot(chrom2.site$POS, chrom2.site$PI_AU, type="n", axes=FALSE, bty="n", ylim=c(0,0.6))
points(chrom2.site$POS, chrom2.site$PI_AU, pch=16,cex=0.5,col = "#F2C14E",axes=FALSE, bty="n", ylim=c(0,0.6))
par(new=T)
points(chrom2.site$POS, chrom2.site$PI_US, pch=16,cex=0.5,col = "#2c81a8", axes=FALSE, xlab=NA, ylab=NA,  bty="n", ylim=c(0,0.6))
axis(side=2, ylim=c(0,0.6))
par(new=T)
points(chrom2.site$POS, chrom2.site$PI_UK, pch=16,cex=0.5,col = "grey50", axes=FALSE, xlab=NA, ylab=NA,  bty="n", ylim=c(0,0.6))
axis(side=1)
quartz.save("/Users/nataliehofmeister/Documents/Ch3-Global-RESEQ/analysis/R/manhattans_for_pub/Chromosome2.SitebySite.pdf", type="pdf")
```
